#!/usr/bin/env zsh

export DOTFILES="$HOME/.kdot"
export STOW_FOLDERS=("nvim" "zsh")

pushd $DOTFILES

for folder in "${STOW_FOLDERS[@]}"; do
  stow -D -v "$folder"
  stow -v "$folder"
done

popd

stow -D -v -t /usr/local/sbin sbin/
stow -v -t /usr/local/sbin sbin/
