#!/usr/bin/env bash
#
# start describes the status of the EC2 instance named INSTANCE_NAME.

set -e
set -x

aws ec2 describe-instances \
    --instance-ids $INSTANCE_ID_KEVIAN \
    --query 'Reservations[].Instances[].State.Name' \
    --output text

